//! Reflection-based conversion of an arbitrary `GameCommand` payload into a
//! `serde_json::Value`.
//!
//! `CMD_ID_MESSAGES` is generated by `build.rs` from the `// CmdId: N` comments
//! in the V70 Starlight protos, mapping each command id to its body message
//! name. At call time we look up that message's `MessageDescriptor`, parse the
//! decrypted payload as a dynamic message, and recursively enumerate its
//! fields without needing a concrete generated Rust type per command.

use base64::Engine;
use protobuf::reflect::ReflectValueRef;
use protobuf::MessageDyn;

use crate::GameCommand;

include!(concat!(env!("OUT_DIR"), "/cmd_id_map.rs"));

/// Resolve a command id to its body message name and descriptor via the
/// `CMD_ID_MESSAGES` map generated by `build.rs`.
fn resolve_message(command_id: u16) -> Option<(String, protobuf::reflect::MessageDescriptor)> {
    let fd = crate::r#gen::protos::file_descriptor();
    let name = CMD_ID_MESSAGES
        .iter()
        .find(|(id, _)| *id == command_id)
        .map(|(_, name)| *name)?;
    // `message_by_full_name` requires a fully-qualified name beginning with
    // a dot; message names here carry no package, so prefix it.
    let desc = fd.message_by_full_name(&format!(".{name}"))?;
    Some((name.to_owned(), desc))
}

/// Serialize a single decoded `GameCommand` to `{cmd_id, name, size, data}`.
/// Returns `None` when the command id has no known body message type.
pub fn command_to_json(cmd: &GameCommand) -> Option<serde_json::Value> {
    let (name, desc) = resolve_message(cmd.command_id)?;

    let base = serde_json::json!({
        "cmd_id": cmd.command_id,
        "name": name,
        "direction": cmd.direction_str(),
        "header_len": cmd.header_len,
        "size": cmd.proto_data.len(),
    });

    match desc.parse_from_bytes(&cmd.proto_data) {
        Ok(msg) => {
            let data = msg_to_value(&*msg);
            let mut v = base;
            v["data"] = data;
            Some(v)
        }
        Err(e) => {
            let mut v = base;
            v["parse_error"] = serde_json::json!(e.to_string());
            v["raw"] = serde_json::json!(base64::engine::general_purpose::STANDARD
                .encode(&cmd.proto_data));
            Some(v)
        }
    }
}

/// Serialize a lightweight summary of a `GameCommand` for list display:
/// `{cmd_id, name, direction, header_len, size, field_count, brief_keys}`.
///
/// Parses the body to count present fields and collect up to four top-level
/// field names, but never serializes field values, so the cost stays
/// proportional to the message schema, not the payload size. `name` is
/// `"unknown"`, `field_count` null and `brief_keys` empty when the command id
/// has no known body message; `parse_error` is set when the body fails to
/// decode.
pub fn command_summary_json(cmd: &GameCommand) -> serde_json::Value {
    let mut base = serde_json::json!({
        "cmd_id": cmd.command_id,
        "name": "unknown",
        "direction": cmd.direction_str(),
        "header_len": cmd.header_len,
        "size": cmd.proto_data.len(),
        "field_count": serde_json::Value::Null,
        "brief_keys": [],
    });

    let Some((name, desc)) = resolve_message(cmd.command_id) else {
        return base;
    };
    base["name"] = serde_json::Value::String(name);

    match desc.parse_from_bytes(&cmd.proto_data) {
        Ok(msg) => {
            let desc = msg.descriptor_dyn();
            let mut field_count = 0usize;
            let mut brief_keys: Vec<serde_json::Value> = Vec::new();
            for field in desc.fields() {
                let present = if field.is_map() {
                    !field.get_map(&*msg).is_empty()
                } else if field.is_repeated() {
                    !field.get_repeated(&*msg).is_empty()
                } else {
                    field.has_field(&*msg)
                };
                if present {
                    field_count += 1;
                    if brief_keys.len() < 4 {
                        brief_keys
                            .push(serde_json::Value::String(field.json_name().to_owned()));
                    }
                }
            }
            base["field_count"] = serde_json::Value::from(field_count);
            base["brief_keys"] = serde_json::Value::Array(brief_keys);
        }
        Err(_) => {
            base["parse_error"] = serde_json::Value::Bool(true);
        }
    }
    base
}

/// Recursively serialize a parsed message into a JSON object. Only emits
/// fields that are actually present; map/repeated entries that are empty are
/// omitted.
fn msg_to_value(m: &dyn MessageDyn) -> serde_json::Value {
    let desc = m.descriptor_dyn();
    let mut obj = serde_json::Map::new();
    for field in desc.fields() {
        let key = field.json_name().to_owned();
        if field.is_map() {
            let map = field.get_map(m);
            if map.is_empty() {
                continue;
            }
            let mut inner = serde_json::Map::new();
            for (k, v) in &map {
                inner.insert(key_string(&k).to_owned(), value_to_json(&v));
            }
            obj.insert(key, serde_json::Value::Object(inner));
        } else if field.is_repeated() {
            let rep = field.get_repeated(m);
            if rep.is_empty() {
                continue;
            }
            let mut arr = Vec::new();
            for v in &rep {
                arr.push(value_to_json(&v));
            }
            obj.insert(key, serde_json::Value::Array(arr));
        } else if field.has_field(m) {
            if let Some(v) = field.get_singular(m) {
                obj.insert(key, value_to_json(&v));
            }
        }
    }
    serde_json::Value::Object(obj)
}

fn value_to_json(v: &ReflectValueRef) -> serde_json::Value {
    match v {
        ReflectValueRef::U32(x) => (*x).into(),
        ReflectValueRef::U64(x) => (*x).into(),
        ReflectValueRef::I32(x) => (*x).into(),
        ReflectValueRef::I64(x) => (*x).into(),
        ReflectValueRef::F32(x) => (f64::from(*x)).into(),
        ReflectValueRef::F64(x) => (*x).into(),
        ReflectValueRef::Bool(x) => (*x).into(),
        ReflectValueRef::String(s) => (*s).into(),
        ReflectValueRef::Bytes(b) => {
            serde_json::Value::from(base64::engine::general_purpose::STANDARD.encode(b))
        }
        ReflectValueRef::Enum(_e, num) => (*num).into(),
        ReflectValueRef::Message(m) => msg_to_value(&**m),
    }
}

/// Convert a map key to an owned `String` (protobuf JSON map keys must be the
/// string form; falls back to the `Display` encoding of the scalar value).
fn key_string(k: &ReflectValueRef) -> String {
    match k {
        ReflectValueRef::String(s) => (*s).to_owned(),
        other => other.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use protobuf::Message;

    use super::*;
    use crate::PacketDirection;
    use crate::r#gen::protos::{AvatarDataNotify, AvatarTeam};

    fn fd() -> &'static protobuf::reflect::FileDescriptor {
        crate::r#gen::protos::file_descriptor()
    }

    fn resolve(name: &str) -> Option<protobuf::reflect::MessageDescriptor> {
        fd().message_by_full_name(&format!(".{name}"))
    }

    #[test]
    fn cmd_id_map_is_unique() {
        let mut ids: Vec<u16> = CMD_ID_MESSAGES.iter().map(|(id, _)| *id).collect();
        ids.sort_unstable();
        let total = ids.len();
        ids.dedup();
        assert_eq!(ids.len(), total, "duplicate cmd_id entries in CMD_ID_MESSAGES");
        assert!(!ids.is_empty(), "CMD_ID_MESSAGES should not be empty");
    }

    #[test]
    fn cmd_id_map_names_all_resolve() {
        for (id, name) in CMD_ID_MESSAGES {
            assert!(
                resolve(name).is_some(),
                "cmd_id {id} maps to unknown message {name}"
            );
        }
    }

    #[test]
    fn unknown_cmd_returns_none() {
        let cmd = GameCommand {
            command_id: 0xFFFF,
            header_len: 0,
            data_len: 0,
            proto_data: Vec::new(),
            ext_header: Vec::new(),
            direction: PacketDirection::Received,
        };
        assert!(cmd.to_json().is_none());
    }

    #[test]
    fn summary_json_shape() {
        let unknown = GameCommand {
            command_id: 0xFFFF,
            header_len: 0,
            data_len: 0,
            proto_data: Vec::new(),
            ext_header: Vec::new(),
            direction: PacketDirection::Sent,
        };
        let s = crate::proto_json::command_summary_json(&unknown);
        assert_eq!(s["name"], "unknown");
        assert!(s["field_count"].is_null());
        assert_eq!(s["brief_keys"], serde_json::json!([]));
        assert!(s.get("data").is_none());

        let mut body = AvatarDataNotify::new();
        body.cur_avatar_team_id = 7;
        body.owned_costume_list.push(1);
        let bytes = Message::write_to_bytes(&body).unwrap();
        let cmd = GameCommand {
            command_id: 6586,
            header_len: 0,
            data_len: bytes.len() as u32,
            proto_data: bytes,
            ext_header: Vec::new(),
            direction: PacketDirection::Sent,
        };
        let s = cmd.summary_json();
        assert_eq!(s["name"], "AvatarDataNotify");
        assert_eq!(s["field_count"], 2);
        assert_eq!(
            s["brief_keys"],
            serde_json::json!(["ownedCostumeList", "curAvatarTeamId"])
        );
        assert!(s.get("data").is_none());
    }

    #[test]
    fn roundtrip_avatar_data_notify() {
        let mut body = AvatarDataNotify::new();
        body.cur_avatar_team_id = 7;
        body.choose_avatar_guid = 99;
        body.owned_costume_list.push(1);
        body.owned_costume_list.push(2);
        body.backup_avatar_team_order_list.push(3);
        body.temp_avatar_guid_list.push(1234);
        body.avatar_team_map.insert(5, AvatarTeam::new());

        let bytes = Message::write_to_bytes(&body).unwrap();
        let cmd = GameCommand {
            command_id: 6586,
            header_len: 0,
            data_len: bytes.len() as u32,
            proto_data: bytes,
            ext_header: Vec::new(),
            direction: PacketDirection::Sent,
        };

        let json = cmd.to_json().expect("AvatarDataNotify is a known command");
        assert_eq!(json["cmd_id"], 6586);
        assert_eq!(json["name"], "AvatarDataNotify");
        assert_eq!(json["direction"], "sent");
        assert_eq!(json["size"], cmd.proto_data.len() as u64);

        let data = &json["data"];
        assert_eq!(data["curAvatarTeamId"], 7);
        assert_eq!(data["chooseAvatarGuid"], 99);
        assert_eq!(data["ownedCostumeList"], serde_json::json!([1, 2]));
        assert_eq!(data["backupAvatarTeamOrderList"], serde_json::json!([3]));
        assert_eq!(data["tempAvatarGuidList"], serde_json::json!([1234]));
        // map key is stringified; empty AvatarTeam value serializes to {}
        assert!(data["avatarTeamMap"].get("5").is_some());
        assert_eq!(data["avatarTeamMap"]["5"], serde_json::json!({}));
    }

    #[test]
    fn known_cmd_garbage_bytes_yields_parse_error() {
        let cmd = GameCommand {
            command_id: 6586,
            header_len: 0,
            data_len: 5,
            proto_data: vec![0xFF, 0xFF, 0xFF, 0xFF, 0xFF],
            ext_header: Vec::new(),
            direction: PacketDirection::Received,
        };
        let json = cmd.to_json().expect("known command still returns an object");
        assert_eq!(json["name"], "AvatarDataNotify");
        assert_eq!(json["direction"], "received");
        assert!(json.get("parse_error").is_some());
        assert!(json.get("raw").is_some());
    }
}